### PR TITLE
Fix Issue 26

### PR DESCRIPTION
**Pull request by bahendri**
URL in template did not match URL in get_url function.

### CODE REVIEW

**Comment by davidkrisch** [comment]
This will work in Django 1.9 and 1.10, but I'm not sure it will work in 1.8.  I think #30 will work with Django 1.8, 1.9, and 1.10

**Comment by bahendri** [comment]
I implemented this modification in a project running Django==1.8.7 without a problem, but I'm happy to defer if your patch makes more sense.

Out of curiosity, how does Django 1.9 and 1.10 know that `url(r'^(.+)/change/clone/$',` matches `href="clone/"`?

**Comment by davidkrisch** [comment]
> Out of curiosity, how does Django 1.9 and 1.10 know that `url(r'^(.+)/change/clone/$')`, matches `href="clone/"`?

Django isn't matching `clone/` with `url(r'^(.+)/change/clone/$')`.  The browser takes `clone/` and appends it to the url of the current page.  Running the sample project with Django 1.10, the Change Post page is at `/admin/posts/post/1/change/` which makes the 'Clone It!' link have a path of
`/admin/posts/post/1/change/clone`

**Comment by davidkrisch** [comment]
#30 (I hope) fixes the same issue this tries to address.  Closing this for now.  Thank you for the PR.

**Comment by bahendri** [comment]
Ah, I see, they changed the URLs in 1.9. That explains why nobody else was having problems. Thanks for addressing this so quickly.

**Pull request closed without merging**
